language: node_js #设置语言

node_js: 
  - "8" #设置语言版本

cache:
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo generate 

#after_script前5句是把部署分支的.git文件夹保护起来，用于保留历史部署的commit日志，否则部署分支永远只有一条commit记录。
#命令里面的变量都是在Travis CI里配置过的。 
# E: Build LifeCycle

# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
    
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GT_Token
    local_dir: public 
    name: $GT_USER
    email: $GT_EMAIL
    fqdn: $Domain